#cloud-config

---
ssh_authorized_keys:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjMwxzh/EFR0qgV6GqLP0POrtDQOn7BTkCSLtnK6yLqMvrWkPgq4Lcowys1uyupCkGgtn56oYj/cCctCmTpn8qu/9JKZEGvqlJ/ObmPS+4lab8Ar7KSk5gqMLnZn0/NnWE8OtO/NZRx6CdxLK10kbm4/hebbB3mRS4QRq0ioL/FbzMITFJaQN6SEdNs646UA0xzFB4QY6JLKftUpwRqFseurINRZi++gfc6RvCyOCmqBMWDSk6ld9J2ZfLs0dOMjETQ6aL8xhjZqiMKz7DTsm1ZalvrctYwunLUDVwxRXziSd6ixYBLNg5o5Xv2AD8TVb4QISDF8b0QgYHRCOYsqNX'
